[colors.primary]
background = "#1E1E1E"
foreground = "#E0E0E0"

[colors.cursor]
text = "#2A2A2A"
cursor = "#38D5D5"

[colors.selection]
background = "#38D5D5"
text = "#2A2A2A"

[colors.normal]
black = "#919191"
red = "#F34E4E"
green = "#36DB36"
yellow = "#CFCF2A"
blue = "#7E7EFF"
magenta = "#E742E7"
cyan = "#38D5D5"
white = "#E0E0E0"

# Bright variant is bloat
[colors.bright]
black = "#919191"
red = "#F34E4E"
green = "#36DB36"
yellow = "#CFCF2A"
blue = "#7E7EFF"
magenta = "#E742E7"
cyan = "#38D5D5"
white = "#E0E0E0"
