background = #1E1E1E
foreground = #E0E0E0
selection-background = #38D5D5
selection-foreground = #2A2A2A
cursor-color = #38D5D5
cursor-text = #2A2A2A

palette = 0=#919191
palette = 1=#F34E4E
palette = 2=#36DB36
palette = 3=#CFCF2A
palette = 4=#7E7EFF
palette = 5=#E742E7
palette = 6=#38D5D5
palette = 7=#E0E0E0

# Bright variant is bloat
palette = 8=#919191
palette = 9=#F34E4E
palette = 10=#36DB36
palette = 11=#CFCF2A
palette = 12=#7E7EFF
palette = 13=#E742E7
palette = 14=#38D5D5
palette = 15=#E0E0E0

